# Site settings
title: Melissa Writes Code
header-img: img/home-bg.png
email: amaya.melissa@gmail.com
copyright_name: mandlerm
description: > # this means to ignore newlines until "baseurl:"
  journey of a wannabe tech geek
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mandlerm
learn_profile: mandlerm
email_username: amaya.melissa@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
